import React, { useState } from "react";
import { Box, Grid, Typography, Button, darken } from "@mui/material";
import { Link } from "react-router-dom";
import ComparePlayerTable from "../components/ComparePlayerTable.jsx";
import axios from "axios";
import Loading from "../components/Loading.jsx";
import TextField from "@mui/material/TextField";
import Autocomplete from "@mui/material/Autocomplete";

const options = [
  "A.J. Green",
  "A.J. Lawson",
  "Aaron Gordon",
  "Aaron Holiday",
  "Aaron Nesmith",
  "Aaron Wiggins",
  "Admiral Schofield",
  "AJ Griffin",
  "Al Horford",
  "Alec Burks",
  "Aleksej Pokusevski",
  "Alex Caruso",
  "Alex Len",
  "Alize Johnson",
  "Alondes Williams",
  "Alperen Şengün",
  "Amir Coffey",
  "Andre Drummond",
  "Andre Iguodala",
  "Andrew Nembhard",
  "Andrew Wiggins",
  "Anfernee Simons",
  "Anthony Davis",
  "Anthony Edwards",
  "Anthony Gill",
  "Anthony Lamb",
  "Austin Reaves",
  "Austin Rivers",
  "Ayo Dosunmu",
  "Bam Adebayo",
  "Ben Simmons",
  "Bennedict Mathurin",
  "Bismack Biyombo",
  "Blake Griffin",
  "Blake Wesley",
  "Boban Marjanović",
  "Bobby Portis",
  "Bogdan Bogdanović",
  "Bojan Bogdanović",
  "Bol Bol",
  "Bones Hyland",
  "Bradley Beal",
  "Brandon Boston Jr.",
  "Brandon Clarke",
  "Brandon Ingram",
  "Braxton Key",
  "Brook Lopez",
  "Bruce Brown",
  "Bruno Fernando",
  "Bryce McGowens",
  "Bryn Forbes",
  "Buddy Boeheim",
  "Buddy Hield",
  "Cade Cunningham",
  "Caleb Houstan",
  "Caleb Martin",
  "Cam Reddish",
  "Cam Thomas",
  "Cameron Johnson",
  "Cameron Payne",
  "Caris LeVert",
  "Carlik Jones",
  "Cedi Osman",
  "Charles Bassey",
  "Chima Moneke",
  "Chimezie Metu",
  "Chris Boucher",
  "Chris Duarte",
  "Chris Paul",
  "Chris Silva",
  "Christian Braun",
  "Christian Koloko",
  "Christian Wood",
  "Chuma Okeke",
  "CJ McCollum",
  "Clint Capela",
  "Coby White",
  "Cody Martin",
  "Cody Zeller",
  "Cole Anthony",
  "Cole Swider",
  "Collin Sexton",
  "Corey Kispert",
  "Cory Joseph",
  "D'Angelo Russell",
  "Daishen Nix",
  "Dalano Banton",
  "Dalen Terry",
  "Damian Jones",
  "Damian Lillard",
  "Damion Lee",
  "Daniel Gafford",
  "Daniel Theis",
  "Danny Green",
  "Danuel House Jr.",
  "Dario Šarić",
  "Darius Bazley",
  "Darius Days",
  "Darius Garland",
  "David Duke Jr.",
  "David Roddy",
  "Davion Mitchell",
  "Dāvis Bertāns",
  "Davon Reed",
  "Day'Ron Sharpe",
  "De'Aaron Fox",
  "De'Andre Hunter",
  "De'Anthony Melton",
  "Dean Wade",
  "Deandre Ayton",
  "DeAndre Jordan",
  "Dejounte Murray",
  "Delon Wright",
  "DeMar DeRozan",
  "Deni Avdija",
  "Dennis Schröder",
  "Dennis Smith Jr.",
  "Deonte Burton",
  "Dereon Seabron",
  "Derrick Jones Jr.",
  "Derrick Rose",
  "Derrick White",
  "Desmond Bane",
  "Devin Booker",
  "Devin Vassell",
  "Devon Dotson",
  "Devonte' Graham",
  "Dewayne Dedmon",
  "Dillon Brooks",
  "Domantas Sabonis",
  "Dominick Barlow",
  "Donovan Mitchell",
  "Donovan Williams",
  "Donte DiVincenzo",
  "Dorian Finney-Smith",
  "Doug McDermott",
  "Draymond Green",
  "Drew Eubanks",
  "Dru Smith",
  "Duane Washington Jr.",
  "Duncan Robinson",
  "Dwight Powell",
  "Dylan Windler",
  "Dyson Daniels",
  "Edmond Sumner",
  "Eric Gordon",
  "Eugene Omoruyi",
  "Evan Fournier",
  "Evan Mobley",
  "Facundo Campazzo",
  "Frank Jackson",
  "Frank Kaminsky",
  "Frank Ntilikina",
  "Franz Wagner",
  "Fred VanVleet",
  "Furkan Korkmaz",
  "Gabe Vincent",
  "Gabe York",
  "Garrett Temple",
  "Garrison Mathews",
  "Gary Harris",
  "Gary Payton II",
  "Gary Trent Jr.",
  "George Hill",
  "Georges Niang",
  "Giannis Antetokounmpo",
  "Goga Bitadze",
  "Goran Dragić",
  "Gordon Hayward",
  "Gorgui Dieng",
  "Grant Williams",
  "Grayson Allen",
  "Greg Brown III",
  "Hamidou Diallo",
  "Harrison Barnes",
  "Haywood Highsmith",
  "Herbert Jones",
  "Immanuel Quickley",
  "Isaac Okoro",
  "Isaiah Hartenstein",
  "Isaiah Jackson",
  "Isaiah Joe",
  "Isaiah Livers",
  "Isaiah Mobley",
  "Isaiah Roby",
  "Isaiah Stewart",
  "Isaiah Todd",
  "Ish Smith",
  "Ish Wainright",
  "Ivica Zubac",
  "Ja Morant",
  "Jabari Smith Jr.",
  "Jabari Walker",
  "Jack White",
  "Jacob Gilyard",
  "Jaden Hardy",
  "Jaden Ivey",
  "Jaden McDaniels",
  "Jaden Springer",
  "Jae Crowder",
  "Jae'Sean Tate",
  "Jake LaRavia",
  "Jakob Poeltl",
  "Jalen Brunson",
  "Jalen Duren",
  "Jalen Green",
  "Jalen Johnson",
  "Jalen McDaniels",
  "Jalen Smith",
  "Jalen Suggs",
  "Jalen Williams",
  "Jamal Cain",
  "Jamal Murray",
  "Jamaree Bouyea",
  "James Bouknight",
  "James Harden",
  "James Johnson",
  "James Wiseman",
  "JaMychal Green",
  "Jared Butler",
  "Jared Rhoden",
  "Jaren Jackson Jr.",
  "Jarred Vanderbilt",
  "Jarrell Brantley",
  "Jarrett Allen",
  "Jarrett Culver",
  "Jason Preston",
  "JaVale McGee",
  "Javonte Green",
  "Jaxson Hayes",
  "Jay Huff",
  "Jay Scrubb",
  "Jaylen Brown",
  "Jaylen Nowell",
  "Jaylin Williams",
  "Jayson Tatum",
  "JD Davison",
  "Jeenathan Williams",
  "Jeff Dowtin",
  "Jeff Green",
  "Jerami Grant",
  "Jeremiah Robinson-Earl",
  "Jeremy Sochan",
  "Jericho Sims",
  "Jevon Carter",
  "Jimmy Butler",
  "Jock Landale",
  "Joe Harris",
  "Joe Ingles",
  "Joe Wieskamp",
  "Joel Embiid",
  "John Butler",
  "John Collins",
  "John Konchar",
  "John Wall",
  "Johnny Davis",
  "Johnny Juzang",
  "Jonas Valančiūnas",
  "Jonathan Isaac",
  "Jonathan Kuminga",
  "Jordan Clarkson",
  "Jordan Goodwin",
  "Jordan Hall",
  "Jordan McLaughlin",
  "Jordan Nwora",
  "Jordan Poole",
  "Jordan Schakel",
  "Jose Alvarado",
  "Josh Christopher",
  "Josh Giddey",
  "Josh Green",
  "Josh Hart",
  "Josh Minott",
  "Josh Okogie",
  "Josh Richardson",
  "Joshua Primo",
  "Jrue Holiday",
  "JT Thor",
  "Juan Toscano-Anderson",
  "Juancho Hernangómez",
  "Julian Champagnie",
  "Julius Randle",
  "Justin Champagnie",
  "Justin Holiday",
  "Justin Jackson",
  "Justin Minaya",
  "Justise Winslow",
  "Jusuf Nurkić",
  "Kai Jones",
  "Karl-Anthony Towns",
  "Kawhi Leonard",
  "Keegan Murray",
  "Keita Bates-Diop",
  "Keldon Johnson",
  "Kelly Olynyk",
  "Kelly Oubre Jr.",
  "Kemba Walker",
  "Kendall Brown",
  "Kendrick Nunn",
  "Kennedy Chandler",
  "Kenneth Lofton Jr.",
  "Kenrich Williams",
  "Kentavious Caldwell-Pope",
  "Kenyon Martin Jr.",
  "Keon Ellis",
  "Keon Johnson",
  "Kessler Edwards",
  "Kevin Durant",
  "Kevin Huerter",
  "Kevin Knox",
  "Kevin Love",
  "Kevin Porter Jr.",
  "Kevon Harris",
  "Kevon Looney",
  "Khem Birch",
  "Khris Middleton",
  "Killian Hayes",
  "Kira Lewis Jr.",
  "Klay Thompson",
  "Kobi Simmons",
  "Kris Dunn",
  "Kristaps Porziņģis",
  "Kyle Anderson",
  "Kyle Kuzma",
  "Kyle Lowry",
  "Kyrie Irving",
  "KZ Okpala",
  "Lamar Stevens",
  "LaMelo Ball",
  "Landry Shamet",
  "Larry Nance Jr.",
  "Lauri Markkanen",
  "Leandro Bolmaro",
  "LeBron James",
  "Lester Quinones",
  "Lindell Wigginton",
  "Lindy Waters III",
  "Lonnie Walker IV",
  "Louis King",
  "Luguentz Dort",
  "Luka Dončić",
  "Luka Garza",
  "Luka Šamanić",
  "Luke Kennard",
  "Luke Kornet",
  "Mac McClung",
  "Malachi Flynn",
  "Malaki Branham",
  "Malcolm Brogdon",
  "Malcolm Hill",
  "Malik Beasley",
  "Malik Monk",
  "Mamadi Diakite",
  "Marcus Morris",
  "Marcus Smart",
  "MarJon Beauchamp",
  "Mark Williams",
  "Markelle Fultz",
  "Markieff Morris",
  "Marko Simonovic",
  "Marvin Bagley III",
  "Mason Plumlee",
  "Matisse Thybulle",
  "Matt Ryan",
  "Matthew Dellavedova",
  "Max Christie",
  "Max Strus",
  "Maxi Kleber",
  "McKinley Wright IV",
  "Meyers Leonard",
  "Mfiondu Kabengele",
  "Micah Potter",
  "Michael Carter-Williams",
  "Michael Foster Jr.",
  "Michael Porter Jr.",
  "Mikal Bridges",
  "Mike Conley",
  "Mike Muscala",
  "Miles McBride",
  "Mitchell Robinson",
  "Mo Bamba",
  "Monte Morris",
  "Montrezl Harrell",
  "Moritz Wagner",
  "Moses Brown",
  "Moses Moody",
  "Moussa Diabaté",
  "Myles Turner",
  "Naji Marshall",
  "Nassir Little",
  "Nathan Knight",
  "Naz Reid",
  "Neemias Queta",
  "Nerlens Noel",
  "Nic Claxton",
  "Nick Richards",
  "Nickeil Alexander-Walker",
  "Nicolas Batum",
  "Nikola Jokić",
  "Nikola Jović",
  "Nikola Vučević",
  "Noah Vonleh",
  "Norman Powell",
  "Obi Toppin",
  "Ochai Agbaji",
  "OG Anunoby",
  "Olivier Sarr",
  "Omer Yurtseven",
  "Onyeka Okongwu",
  "Orlando Robinson",
  "Oshae Brissett",
  "Otto Porter Jr.",
  "Ousmane Dieng",
  "P.J. Tucker",
  "P.J. Washington",
  "Paolo Banchero",
  "Pascal Siakam",
  "Pat Connaughton",
  "Patrick Baldwin Jr.",
  "Patrick Beverley",
  "Patrick Williams",
  "Patty Mills",
  "Paul George",
  "Paul Reed",
  "Payton Pritchard",
  "Peyton Watson",
  "PJ Dozier",
  "Precious Achiuwa",
  "Quentin Grimes",
  "Quenton Jackson",
  "R.J. Hampton",
  "RaiQuan Gray",
  "Raul Neto",
  "Reggie Bullock",
  "Reggie Jackson",
  "Richaun Holmes",
  "Ricky Rubio",
  "RJ Barrett",
  "Robert Covington",
  "Robert Williams",
  "Robin Lopez",
  "Rodney McGruder",
  "Romeo Langford",
  "Ron Harper Jr.",
  "Royce O'Neale",
  "Rudy Gay",
  "Rudy Gobert",
  "Rui Hachimura",
  "Russell Westbrook",
  "Ryan Arcidiacono",
  "Ryan Rollins",
  "Saben Lee",
  "Saddiq Bey",
  "Sam Hauser",
  "Sam Merrill",
  "Sandro Mamukelashvili",
  "Santi Aldama",
  "Scottie Barnes",
  "Scotty Pippen Jr.",
  "Serge Ibaka",
  "Seth Curry",
  "Shaedon Sharpe",
  "Shai Gilgeous-Alexander",
  "Shake Milton",
  "Shaquille Harrison",
  "Simone Fontecchio",
  "Skylar Mays",
  "Spencer Dinwiddie",
  "Stanley Johnson",
  "Stanley Umude",
  "Stephen Curry",
  "Sterling Brown",
  "Steven Adams",
  "Svi Mykhailiuk",
  "T.J. McConnell",
  "T.J. Warren",
  "Taj Gibson",
  "Talen Horton-Tucker",
  "Tari Eason",
  "Taurean Prince",
  "Terance Mann",
  "Terence Davis",
  "Terrence Ross",
  "Terry Rozier",
  "Terry Taylor",
  "Thaddeus Young",
  "Thanasis Antetokounmpo",
  "Théo Maledon",
  "Theo Pinson",
  "Thomas Bryant",
  "Tim Hardaway Jr.",
  "Tobias Harris",
  "Tony Bradley",
  "Torrey Craig",
  "Trae Young",
  "Tre Jones",
  "Tre Mann",
  "Trendon Watford",
  "Trent Forrest",
  "Trevelin Queen",
  "Trevor Hudgins",
  "Trevor Keels",
  "Trey Lyles",
  "Trey Murphy III",
  "Troy Brown Jr.",
  "Ty Jerome",
  "Tyler Dorsey",
  "Tyler Herro",
  "Tyrese Haliburton",
  "Tyrese Martin",
  "Tyrese Maxey",
  "TyTy Washington Jr.",
  "Tyus Jones",
  "Udoka Azubuike",
  "Udonis Haslem",
  "Usman Garuba",
  "Vernon Carey Jr.",
  "Victor Oladipo",
  "Vince Williams Jr.",
  "Vit Krejci",
  "Vlatko Čančar",
  "Walker Kessler",
  "Wendell Carter Jr.",
  "Wendell Moore Jr.",
  "Wenyen Gabriel",
  "Wesley Matthews",
  "Will Barton",
  "Willy Hernangómez",
  "Xavier Cooks",
  "Xavier Moon",
  "Xavier Sneed",
  "Xavier Tillman Sr.",
  "Yuta Watanabe",
  "Zach Collins",
  "Zach LaVine",
  "Zeke Nnaji",
  "Ziaire Williams",
  "Zion Williamson",
];

const ComparePlayers = ({ darkMode }) => {
  const [loading, setLoading] = useState(false);
  const [player, setPlayer] = useState([]);
  const [value, setValue] = useState(options[0]);
  const [inputValue, setInputValue] = useState("");

  const darkModeButton = {
    mt: 1,
    color: "white",
    border: "1px white solid",
    "&:hover": {
      backgroundColor: darken("#FFFFFF", 0.3),
      borderColor: "white",
    },
  };
  const lightModeButton = {
    mt: 1,
    color: "black",
    border: "1px black solid",
    "&:hover": {
      backgroundColor: darken("#FFFFFF", 0.3),
      borderColor: "black",
    },
  };
  const getData = () => {
    setLoading(true);
    axios
      .get(`http://localhost:3000/players/single/${value}`)
      .then((response) => {
        player.push(response.data);
        setLoading(false);
      })
      .catch((error) => {
        console.log(error.message);
        setLoading(false);
      });
  };

  return (
    <Box sx={{ flexGrow: 1, mt: 2 }}>
      <Typography variant="h2" align="center">
        Compare Players
      </Typography>

      <Grid item align="center" sx={{ mt: 10 }}>
        <Autocomplete
          value={value}
          onChange={(event, newValue) => {
            setValue(newValue);
          }}
          inputValue={inputValue}
          onInputChange={(event, newInputValue) => {
            setInputValue(newInputValue);
          }}
          options={options}
          sx={{ width: 300 }}
          renderInput={(params) => <TextField {...params} label="Players" />}
        />
      </Grid>

      <Grid container spacing={1} sx={{ justifyContent: "center" }}>
        <Grid item>
          <Button
            variant="outlined"
            color="primary"
            sx={darkMode ? darkModeButton : lightModeButton}
            onClick={getData}
          >
            Select
          </Button>
        </Grid>

        <Grid item>
          <Button
            variant="outlined"
            color="error"
            sx={{ mt: 1 }}
            to="/"
            component={Link}
          >
            Back
          </Button>
        </Grid>
      </Grid>

      <Grid item align="center">
        <ComparePlayerTable player={player} />
      </Grid>
    </Box>
  );
};

export default ComparePlayers;
